name: CI React App

on:
  push:
    branches: [homologacao]
  pull_request:
    branches: [main, teste-ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Instalar dependências com npm ci
        run: npm ci
        working-directory: earthmoon/

      - name: Build do projeto React
        run: CI=false npm run build --if-present
        working-directory: earthmoon/